// Objective-C API for talking to pop.ngin Go package.
//   gobind -lang=objc pop.ngin
//
// File is generated by gobind. Do not edit.

#ifndef __Ngin_H__
#define __Ngin_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class NginAPI_KEY;
@class NginCover;
@class NginCoverURL;
@class NginTokens;
@class NginUserLogin;
@class NginUserRegister;

@interface NginAPI_KEY : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull key;
- (BOOL)check;
@end

@interface NginCover : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSData* _Nullable data;
- (NginCoverURL* _Nullable)uploadCover:(NSString* _Nullable)addr;
@end

@interface NginCoverURL : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull url;
@end

@interface NginTokens : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull token;
@end

@interface NginUserLogin : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull email;
@property (nonatomic) NSString* _Nonnull password;
- (NSData* _Nullable)login:(NSString* _Nullable)addr path:(NSString* _Nullable)path;
@end

@interface NginUserRegister : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) BOOL agree;
@property (nonatomic) NSString* _Nonnull email;
@property (nonatomic) NSString* _Nonnull password;
@property (nonatomic) NSString* _Nonnull displayName;
@property (nonatomic) NSString* _Nonnull username;
@property (nonatomic) long age;
@property (nonatomic) NSString* _Nonnull sex;
@property (nonatomic) NSString* _Nonnull country;
@property (nonatomic) NSString* _Nonnull cover_URL;
@property (nonatomic) NSString* _Nonnull cover_mini_URL;
- (void)authJWT:(NSString* _Nullable)addr path:(NSString* _Nullable)path token:(NSString* _Nullable)token;
- (NSString* _Nonnull)register:(NSString* _Nullable)addr path:(NSString* _Nullable)path;
@end

@interface Ngin : NSObject
+ (NSString* _Nonnull) ip;
+ (void) setIP:(NSString* _Nonnull)v;

@end

FOUNDATION_EXPORT void NginPing(NSString* _Nullable addr);

#endif
