
// Objective-C API for talking to the following Go packages
//
//	pop.ngin
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Ngin_FRAMEWORK_H__
#define __Ngin_FRAMEWORK_H__

#include "Ngin.objc.h"
#include "Universe.objc.h"

#endif
