// Objective-C API for talking to pop.ngin Go package.
//   gobind -lang=objc pop.ngin
//
// File is generated by gobind. Do not edit.

#ifndef __Pop_H__
#define __Pop_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


@class PopNgin;

@interface PopNgin : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (nonnull instancetype)init;
@property (nonatomic) NSString* _Nonnull name;
@property (nonatomic) long age;
@property (nonatomic) NSString* _Nonnull key;
- (PopNgin* _Nullable)get:(NSString* _Nullable)adress;
- (PopNgin* _Nullable)getData;
- (void)printData;
- (void)send:(NSString* _Nullable)adress;
- (NSData* _Nullable)toJson;
@end

@interface Pop : NSObject
+ (NSString* _Nonnull) address;
+ (void) setAddress:(NSString* _Nonnull)v;

@end

#endif
