
// Objective-C API for talking to the following Go packages
//
//	pop.ngin
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Pop_FRAMEWORK_H__
#define __Pop_FRAMEWORK_H__

#include "Pop.objc.h"
#include "Universe.objc.h"

#endif
